FROM debian:9
MAINTAINER cam@root.gg

RUN apt-get update && apt-get install -y curl
RUN curl -L https://bootstrap.saltstack.com > /root/bootstrap.sh && chmod +x /root/bootstrap.sh
RUN sh /root/bootstrap.sh -X stable

RUN sed -i "s|#master: salt|master: salt-master|g" /etc/salt/minion

ENTRYPOINT ["salt-minion", "-l", "debug"]

