FROM debian:9
MAINTAINER cam@root.gg

RUN apt-get update && apt-get install -y curl
RUN curl -L https://bootstrap.saltstack.com > /root/bootstrap.sh && chmod +x /root/bootstrap.sh
RUN sh /root/bootstrap.sh -M -N -X stable

RUN sed -i "s|#auto_accept: False|auto_accept: True|g" /etc/salt/master

ENTRYPOINT ["salt-master", "-l", "debug"]
